### ISSUE TITLE
Group 2: Encapsulation, week 2

### ISSUE THREAD

**Issue by IrynaSpyrydonova** [HackYourFutureBelgium/class-9-10#637]
# Task Manager

- _Group 2 _

The main idea of this project is to practice and understand the concepts of encapsulation, Object Oriented Programming, Inheritance and Code Reuse.

- [ ] [repo](https://github.com/IrynaSpyrydonova/encapsulation-list-prototype) (with a complete README)
- [ ] [live demo](https://irynaspyrydonova.github.io/encapsulation-list-prototype/public/index.html)
- Project Planning
 - [ ] [Backlog](https://github.com/_/_/tree/master/project-planning/backlog.md)
- [ ] [Communication](https://github.com/_/_/tree/master/project-planning/backlog.md)
 - [ ] [Development Strategy](https://github.com/_/_/tree/master/project-planning/development-strategy.md)
 - [ ] [Project board](https://github.com/IrynaSpyrydonova/encapsulation-list-prototype/projects/1)
- Implementation
  - [ ] ES Modules (`import`/`export`)
  - [ ] Tests for logic & view methods
  - [ ] Initial state in `src/data.js`
  - [ ] Logs of each user interaction
