### ISSUE TITLE
Group 1,Encapsulation, Week 2

### ISSUE THREAD

**Issue by HazemBittar** [HackYourFutureBelgium/class-9-10#638]
# Task manager

- _group 1_

A very simple JavaScript (OOP) ToDo List made to practice OOP and prototypes skills and encapsulation code.

- [x] [repo](https://github.com/HazemBittar/list-prototype) (with a complete README)
- [x] [live demo](https://hazembittar.github.io/list-prototype/)
- Project Planning
 - [ ] [Backlog]()
- [ ] [Communication]()
 - [ ] [Development Strategy]()
 - [ ] [Project board]( )
- Implementation
  - [x] ES Modules (`import`/`export`)
  - [x] Tests for logic & view methods
  - [x] Initial state in `src/data.js`
  - [x] Logs of each user interaction
