### ISSUE TITLE
Group 5: Encapsulation, week 2

### ISSUE THREAD

**Issue by yildiraykoyuncu** [HackYourFutureBelgium/class-9-10#640]
# Todo App

- _Group 5_
- _Yildiray Koyuncu_
- _Eltayeb Elgaali_
-_Mohamad Musa_

An app that enables you to add multiple todo lists and track your tasks.

- [ ] [repo](https://github.com/yildiraykoyuncu/encapsulation-list-prototype-group-5)
- [ ] [live demo](https://yildiraykoyuncu.github.io/encapsulation-list-prototype-group-5/public/index.html)
- Project Planning
  - [ ] [Backlog](https://github.com/yildiraykoyuncu/encapsulation-list-prototype-group-5/blob/master/project-planning/backlog.md)
  - [ ] [Development Strategy](https://github.com/yildiraykoyuncu/encapsulation-list-prototype-group-5/blob/master/project-planning/development-strategy.md)
  - [ ] [Project board](https://github.com/yildiraykoyuncu/encapsulation-list-prototype-group-5/projects/1?add_cards_query=is%3Aopen)
- Implementation
  - [ ] Tests for core app object
  - [ ] Tests for views (optional)
  - [ ] Initial state in `src/data.js`
  - [ ] Logs of each user interaction
